name: Releases

on: 
  push:
    branches:
      - "main"

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        generateReleaseNotes: true
        prerelease: ${{ endsWith(github.ref, 'Development Build') }}
        artifacts: "*"
