name: Nightly Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: nightly-$(date +'%Y%m%d')
          prerelease: true
          files: '**/*'
          title: Nightly Release $(date +'%Y-%m-%d')
